version: '3.8'

services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - ./redis_data:/data 

  server:
    build: ./servidor
    depends_on:
      - redis
    ports:
      - '5000:5000' 
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./servidor:/app

  editor:
    build: ./editor
    depends_on:
      - server
    volumes:
      - ./editor:/app

  client:
    build: ./cliente
    depends_on:
      - server
    volumes:
      - ./cliente:/app